// IconsRes.h
//{{NO_DEPENDENCIES}}
// Used by IconsRes.rc
//

#ifndef ICONSRES_H_
#define ICONSRES_H_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#define IDI_ANALYSISSERVER								1100
#define IDI_ANALYSISSERVERERROR					1101
#define IDI_ANALYSISSERVERPAUSED				1102
#define IDI_ANALYSISSERVERRUNNING				1103
#define IDI_ANALYSISSERVERSTOPED				1104
#define IDI_ANALYSISSERVERSUPRESS				1105
#define IDI_ANALYSISSERVERUNKNOWN				1106
	
#define IDI_FULLTEXTSEARCH								1110
#define IDI_FULLTEXTSEARCHERROR					1111
#define IDI_FULLTEXTSEARCHPAUSED					1112
#define IDI_FULLTEXTSEARCHRUNNING				1113
#define IDI_FULLTEXTSEARCHSTOPED					1114
#define IDI_FULLTEXTSEARCHSUPRESS				1115
#define IDI_FULLTEXTSEARCHUNKNOWN				1116
	
#define IDI_INTEGRATIONSERVICES						1120
#define IDI_INTEGRATIONSERVICESERROR			1121
#define IDI_INTEGRATIONSERVICESPAUSED		1122
#define IDI_INTEGRATIONSERVICESRUNNING		1123
#define IDI_INTEGRATIONSERVICESSTOPED		1124
#define IDI_INTEGRATIONSERVICESSUPRESS		1125
#define IDI_INTEGRATIONSERVICESUNKNOWN	1126
	
#define IDI_MSDTC												1130
#define IDI_MSDTCERROR									1131
#define IDI_MSDTCPAUSED									1132
#define IDI_MSDTCRUNNING									1133
#define IDI_MSDTCSTOPED									1134
#define IDI_MSDTCSUPRESS								1135
#define IDI_MSDTCUNKNOWN								1136
	
#define IDI_NOTIFICATIONSERVICES						1140
#define IDI_NOTIFICATIONSERVICESERROR			1141
#define IDI_NOTIFICATIONSERVICESPAUSED		1142
#define IDI_NOTIFICATIONSERVICESRUNNING		1143
#define IDI_NOTIFICATIONSERVICESSTOPED		1144
#define IDI_NOTIFICATIONSERVICESSUPRESS		1145
#define IDI_NOTIFICATIONSERVICESUNKNOWN	1146
	
#define IDI_REPORTSERVER								1150
#define IDI_REPORTSERVERERROR						1151
#define IDI_REPORTSERVERPAUSED					1152
#define IDI_REPORTSERVERRUNNING					1153
#define IDI_REPORTSERVERSTOPED					1154
#define IDI_REPORTSERVERSUPRESS					1155
#define IDI_REPORTSERVERUNKNOWN				1156
	
#define IDI_SERVER												1160
#define IDI_SERVERERROR									1161
#define IDI_SERVERPAUSED								1162
#define IDI_SERVERRUNNING								1163
#define IDI_SERVERSTOPED								1164
#define IDI_SERVERSUPRESS								1165
#define IDI_SERVERUNKNOWN								1166
	
#define IDI_SQLSERVERADHELPER						1170
#define IDI_SQLSERVERADHELPERERROR			1171
#define IDI_SQLSERVERADHELPERPAUSED		1172
#define IDI_SQLSERVERADHELPERRUNNING		1173
#define IDI_SQLSERVERADHELPERSTOPED		1174
#define IDI_SQLSERVERADHELPERSUPRESS		1175
#define IDI_SQLSERVERADHELPERUNKNOWN		1176
	
#define IDI_SQLSERVERAGENT							1180
#define IDI_SQLSERVERAGENTERROR					1181
#define IDI_SQLSERVERAGENTPAUSED				1182
#define IDI_SQLSERVERAGENTRUNNING				1183
#define IDI_SQLSERVERAGENTSTOPED				1184
#define IDI_SQLSERVERAGENTSUPRESS			1185
#define IDI_SQLSERVERAGENTUNKNOWN			1186
	
#define IDI_SQLSERVERBROWSER						1190
#define IDI_SQLSERVERBROWSERERROR			1191
#define IDI_SQLSERVERBROWSERPAUSED			1192
#define IDI_SQLSERVERBROWSERRUNNING		1193
#define IDI_SQLSERVERBROWSERSTOPED			1194
#define IDI_SQLSERVERBROWSERSUPRESS		1195
#define IDI_SQLSERVERBROWSERUNKNOWN		1196
	
#define IDI_SQLSERVER										1200
#define IDI_SQLSERVERERROR							1201
#define IDI_SQLSERVERPAUSED							1202
#define IDI_SQLSERVERRUNNING							1203
#define IDI_SQLSERVERSTOPED							1204
#define IDI_SQLSERVERSUPRESS						1205
#define IDI_SQLSERVERUNKNOWN						1206
	
#define IDI_SQLWRITER										1210
#define IDI_SQLWRITERERROR								1211
#define IDI_SQLWRITERPAUSED							1212
#define IDI_SQLWRITERRUNNING							1213
#define IDI_SQLWRITERSTOPED							1214
#define IDI_SQLWRITERSUPRESS						1215
#define IDI_SQLWRITERUNKNOWN						1216
	
#define IDI_START													1220
#define IDI_START_D												1221
#define IDI_STOP													1222
#define IDI_STOP_D												1223
#define IDI_PAUSE												1224
#define IDI_PAUSE_D											1225

#endif // ICONSRES_H_
